CREATE TABLE Region (
	Region_ID NUMBER CONSTRAINT Region_ID_PK PRIMARY KEY,
	Region_Name VARCHAR2 (20) NOT NULL
);

DROP TABLE USER_INFO;

CREATE TABLE User_Info (
	User_ID NUMBER CONSTRAINT User_ID_PK PRIMARY KEY,
	User_Name VARCHAR2 (50) NOT NULL,
	Cell_No VARCHAR2 (15) NOT NULL,
	Email VARCHAR2 (50),
	pwd VARCHAR2 (50) NOT NULL
);

CREATE TABLE LANDMARKS (
	LANDMARK_ID NUMBER CONSTRAINT LANDMARK_ID_PK PRIMARY KEY,
	OPENING_DAYS VARCHAR2 (100) NOT NULL,
	GENRE VARCHAR2 (20) NOT NULL,
	DESCRIPTION VARCHAR2 (1000) NOT NULL,
	ADDITIONAL_COST NUMBER NOT NULL,
	REGION_ID NUMBER,
	ROAD_NO VARCHAR2 (10),
	AREA_NAME VARCHAR2 (30) NOT NULL,
	DISTRICT VARCHAR2 (30) NOT NULL,
	OPENING_TIME VARCHAR2 (20),
	CLOSING_TIME VARCHAR2 (20),
	RATING_COUNT NUMBER,
	RATING NUMBER,
	CONSTRAINT LANDMARK_ID_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE VISITED_LANDMARKS (
	USER_ID NUMBER,
	LANDMARK_ID NUMBER,
	RATING NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT VISITED_LANDMARKS_FK1 FOREIGN KEY (LANDMARK_ID) REFERENCES LANDMARKS (LANDMARK_ID),
	CONSTRAINT VISITED_LANDMARKS_FK2 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID)
);

CREATE TABLE HOTELS_AND_RESORTS (
	PLACE_ID NUMBER CONSTRAINT PLACE_ID_PK PRIMARY KEY,
	REGION_ID NUMBER,
	KIND VARCHAR2 (10),
	HOUSE_NO VARCHAR2 (10),
	ROAD_NO VARCHAR2 (10) NOT NULL,
	AREA_NAME VARCHAR2 (20) NOT NULL,
	DISTRICT VARCHAR2 (20) NOT NULL,
	MAXIMUM_COST NUMBER NOT NULL,
	MINIMUM_COST NUMBER NOT NULL,
	RATING NUMBER,
	RATING_COUNT NUMBER,
	CONSTRAINT PLACES_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE STAYED_AT (
	USER_ID NUMBER,
	REGION_ID NUMBER,
	PLACE_ID NUMBER,
	CHECK_IN DATE,
	CHECK_OUT DATE,
	CONSTRAINT STAYED_AT_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT STAYED_AT_FK2 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID),
	CONSTRAINT STAYED_AT_FK3 FOREIGN KEY (PLACE_ID) REFERENCES HOTELS_AND_RESORTS (PLACE_ID)
);

CREATE TABLE INTER_REGION_TRANSPORT (
	INTER_REGION_TRANSPORT_ID NUMBER CONSTRAINT INTER_REGION_PK PRIMARY KEY,
	FROM_DIST NUMBER,
	TO_DIST NUMBER,
	EXPENSE NUMBER NOT NULL,
	MODE_OF_TRANSPORT VARCHAR2 (20),
	VEHICLE_NAME VARCHAR2 (20),
	POPULARITY NUMBER,
	POPULARITY_COUNT NUMBER,
	CONSTRAINT INTER_REGION_FK1 FOREIGN KEY (FROM_DIST) REFERENCES REGION (REGION_ID),
	CONSTRAINT INTER_REGION_FK2 FOREIGN KEY (TO_DIST) REFERENCES REGION (REGION_ID)
);

CREATE TABLE USED_INTER_REGION_TRANSPORT (
	USER_ID NUMBER,
	INTER_REGION_TRANSPORT_ID NUMBER,
	RATING NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT USED_INTER_REGION_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT USED_INTER_REGION_FK2 FOREIGN KEY (INTER_REGION_TRANSPORT_ID) REFERENCES INTER_REGION_TRANSPORT (INTER_REGION_TRANSPORT_ID)
);

CREATE TABLE INTRA_REGION_TRANSPORT (
	INTRA_REGION_TRANSPORT_ID NUMBER CONSTRAINT INTRA_REGION_PK PRIMARY KEY,
	FROM_DEST VARCHAR2 (20),
	TO_DEST VARCHAR2 (20),
	EXPENSE NUMBER NOT NULL,
	MODE_OF_TRANSPORT VARCHAR2 (20),
	VEHICLE_NAME VARCHAR2 (20),
	POPULARITY NUMBER,
	POPULARITY_COUNT NUMBER
);

CREATE TABLE USED_INTRA_REGION_TRANSPORT (
	USER_ID NUMBER,
	INTRA_REGION_TRANSPORT_ID NUMBER,
	RATING NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT USED_INTRA_REGION_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT USED_INTRA_REGION_FK2 FOREIGN KEY (INTRA_REGION_TRANSPORT_ID) REFERENCES INTRA_REGION_TRANSPORT (INTRA_REGION_TRANSPORT_ID)
);

CREATE TABLE RESTAURANTS (
	RESTAURANT_ID NUMBER CONSTRAINT RESTAURANT_ID_PK PRIMARY KEY,
	REGION_ID NUMBER,
	HOUSE_NO VARCHAR2 (10),
	ROAD_NO VARCHAR2 (10) NOT NULL,
	AREA_NAME VARCHAR2 (20) NOT NULL,
	DISTRICT VARCHAR2 (20) NOT NULL,
	AVERAGE_COST NUMBER NOT NULL,
	CONTACT_INFO VARCHAR2 (20),
	RATING NUMBER,
	RATING_COUNT NUMBER,
	CONSTRAINT RESTAURANT_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE VISITED_RESTAURANTS (
	USER_ID NUMBER,
	RESTAURANT_ID NUMBER,
	RATING NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT VISITED_RESTAURANT_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT VISITED_RESTAURANT_FK2 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);

CREATE TABLE EMERGENCY_SERVICES (
	EMERGENCY_ID NUMBER CONSTRAINT EMERGENCY_PK PRIMARY KEY,
	REGION_ID NUMBER,
	KIND VARCHAR2 (20) NOT NULL,
	HOUSE_NO VARCHAR2 (10),
	ROAD_NO VARCHAR2 (10) NOT NULL,
	AREA_NAME VARCHAR2 (20) NOT NULL,
	DISTRICT VARCHAR2 (20) NOT NULL,
	CONTACT_INFO VARCHAR2 (20),
	CONSTRAINT EMERGENCY_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE AVAILED_EMERGENCY (
	USER_ID NUMBER,
	REGION_ID NUMBER,
	EMERGENCY_ID NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT AVAILED_EMERGENCY_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT AVAILED_EMERGENCY_FK2 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID),
	CONSTRAINT AVAILED_EMERGENCY_FK3 FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_SERVICES (EMERGENCY_ID)
);

CREATE TABLE SHOPPING (
	SHOPPING_ID NUMBER CONSTRAINT SHOPPING_PK PRIMARY KEY,
	REGION_ID NUMBER,
	HOUSE_NO VARCHAR2 (10),
	ROAD_NO VARCHAR2 (10) NOT NULL,
	AREA_NAME VARCHAR2 (20) NOT NULL,
	DISTRICT VARCHAR2 (20) NOT NULL,
	OPEN_HOURS VARCHAR2 (30),
	OPEN_DAYS VARCHAR2 (100),
	CONSTRAINT SHOPPING_FK FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);

CREATE TABLE VISITED_MARKETS (
	USER_ID NUMBER,
	--PLAN_ID NUMBER,
	REGION_ID NUMBER,
	SHOPPING_ID NUMBER,
	VISIT_DATE DATE,
	CONSTRAINT VISITED_MARKETS_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT VISITED_MARKETS_FK2 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID),
	CONSTRAINT VISITED_MARKETS_FK3 FOREIGN KEY (SHOPPING_ID) REFERENCES SHOPPING (SHOPPING_ID) --,
	--CONSTRAINT VISITED_MARKETS_FK4 FOREIGN KEY(PLAN_ID) REFERENCES PLANS(PLAN_ID)
);

CREATE TABLE PLANS (
	PLAN_ID NUMBER CONSTRAINT PLANS_PK PRIMARY KEY,
	USER_ID NUMBER,
	LANDMARK_ID NUMBER,
	HOTEL_ID NUMBER,
	RESTAURANT_ID NUMBER,
	INTER_REGION_TRANSPORT_ID NUMBER,
	INTRA_REGION_TRANSPORT_ID NUMBER,
	SHOPPING_ID NUMBER,
	EMERGENCY_ID NUMBER,
	CONSTRAINT PLANS_FK1 FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
	CONSTRAINT PLANS_FK2 FOREIGN KEY (LANDMARK_ID) REFERENCES LANDMARKS (LANDMARK_ID),
	CONSTRAINT PLANS_FK3 FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS_AND_RESORTS (PLACE_ID),
	CONSTRAINT PLANS_FK4 FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID),
	CONSTRAINT PLANS_FK5 FOREIGN KEY (INTER_REGION_TRANSPORT_ID) REFERENCES INTER_REGION_TRANSPORT (INTER_REGION_TRANSPORT_ID),
	CONSTRAINT PLANS_FK6 FOREIGN KEY (INTRA_REGION_TRANSPORT_ID) REFERENCES INTRA_REGION_TRANSPORT (INTRA_REGION_TRANSPORT_ID),
	CONSTRAINT PLANS_FK7 FOREIGN KEY (SHOPPING_ID) REFERENCES SHOPPING (SHOPPING_ID),
	CONSTRAINT PLANS_FK8 FOREIGN KEY (EMERGENCY_ID) REFERENCES EMERGENCY_SERVICES (EMERGENCY_ID)
);

ALTER TABLE USER_INFO ADD PWD VARCHAR2 (20);

ALTER TABLE RESTAURANTS ADD RESTAURANT_NAME VARCHAR2 (100);

ALTER TABLE LANDMARKS ADD LANDMARK_NAME VARCHAR2 (100);

CREATE SEQUENCE REGION_ID_VAL INCREMENT BY 1 START WITH 1 MAXVALUE 10000 NOCYCLE;

ALTER TABLE SHOPPING ADD SHOP_NAME VARCHAR2 (100);

ALTER TABLE HOTELS_AND_RESORTS ADD HOTEL_NAME VARCHAR2 (100);
ALTER TABLE VISITED_MARKETS DROP COLUMN REGION_ID ;
ALTER TABLE EMERGENCY_SERVICES ADD EMERGENCY_NAME VARCHAR2 (100);